services:
  - type: web
    name: doc-analyzer-api
    env: node
    plan: free
    buildCommand: npm ci && npm install --save-dev @types/cors && npm run build
    startCommand: npm run start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: DATABASE_URL
        sync: false
      - key: REDIS_URL
        sync: false
      - key: OPENAI_API_KEY
        sync: false
      - key: UPSTASH_REDIS_PASSWORD
        sync: false
      - key: QDRANT_URL
        sync: false
      - key: QDRANT_API_KEY
        sync: false
      - key: CLEANUP_VECTOR_STORE
        value: "false"
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_KEY
        sync: false
    healthCheckPath: /health
  
  - type: worker
    name: doc-analyzer-worker
    env: node
    plan: free
    buildCommand: npm ci && npm run build
    startCommand: node dist/workers/documentWorker.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        sync: false
      - key: REDIS_URL
        sync: false
      - key: OPENAI_API_KEY
        sync: false
      - key: UPSTASH_REDIS_PASSWORD
        sync: false
      - key: QDRANT_URL
        sync: false
      - key: QDRANT_API_KEY
        sync: false
      - key: CLEANUP_VECTOR_STORE
        value: "false"
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_KEY
        sync: false